server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.37.1:3306/test
    username: test
    password: 1q1w1e1r
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: info

