server:
  port: 8081
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER

security:
  oauth2:
    client:
      client-id: MemberSystem
      client-secret: 12345
      access-token-uri: http://192.168.37.131:8080/oauth/token
      user-authorization-uri: http://192.168.37.131:8080/oauth/authorize
    resource:
      user-info-uri: http://192.168.37.131:8080/user/me
logging:
  level:
    root: info
spring:
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
#spring.main.allow-bean-definition-overriding = true